### ISSUE TITLE
PipelineRun Doesn't Trigger

### ISSUE THREAD

**Issue by danielhelfand** [openshift-labs/lab-openshift-pipelines-with-tekton#12]
It is a known [issue](https://github.com/tektoncd/pipeline/issues/1045) that Tekton does not deal well with minimums specified on `LimitRanges`. The usual workaround is to not set a minimum for Pod/Container resources in terms of CPU and memory. 

However, that does not work for this workshop. After setting minimums for a project's `LimitRange` to 0, triggering a `pipelinerun` causes a new error:

```
Missing or invalid Task
              lab-openshift-pipelines-with-tekton-workshops-gg3wz/s2i-java-8:
              pods "deploy-pipeline-run-t827h-build-gcrjc-pod-ab2d42" is
              forbidden: maximum memory usage per Pod is 8Gi, but limit is
              17179869184.
```

There needs to be a way to set the `LimitRanges` used by the projects generated by Homeroom to the appropriate conditions for the tutorial to succeed.

**Comment by danielhelfand** [comment]
The solution here is that Homeroom will need to provision a project with a `LimitRange` with the following specifications:

```yaml
apiVersion: v1
kind: LimitRange
metadata:
  annotations:
    resource-budget: x-large
  name: resource-limits
  namespace: lab-openshift-pipelines-with-tekton-workshops-mmd30
spec:
  limits:
  - max:
      cpu: "8"
      memory: 8Gi
    type: Pod
  - default:
      cpu: 250m
      memory: 256Mi
    defaultRequest:
      cpu: 50m
      memory: 128Mi
    max:
      cpu: "8"
      memory: 8Gi
    type: Container
  - max:
      storage: 20Gi
    min:
      storage: 1Gi
    type: PersistentVolumeClaim
```

This completely removes the minimums from the `LimitRange` for pods and containers and also specifies a default and defaultRequest that will not exceed the maximum values specified. 

As of now, Homeroom does not feature a way to specify a custom `LimitRange`, but this can be addressed as soon as this feature is added.
